services:
    planechase:
        image: ghcr.io/ionaru/planechase/planechase:latest
        build:
            context: .
        restart: unless-stopped
        ports:
            - '${PLANECHASE_PORT:-80}:80'
